language: android

sudo: true

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository

script: sh ./etc/scripts/test.sh false

after_script: sh ./etc/scripts/uploadReports.sh
