language: android

sudo: true

jdk:
  - oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - tools
  - android-25
  - addon-google_apis-google-25
  - extra-google-m2repository
  - extra-android-m2repository
  - android-sdk-license-.+

script: sh ./etc/scripts/test.sh false

after_script: sh ./etc/scripts/uploadReports.sh
