language: android

sudo: true

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository

script: sh ./etc/scripts/test.sh true false true true true
