language: android

sudo: true

jdk:
  - oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - tools
  - android-25
  - addon-google_apis-google-25
  - extra-google-m2repository
  - extra-android-m2repository
  - android-sdk-license-.+

script:
  - ./gradlew clean testDebug lintDebug connectedAndroidTest -PFIREBASE_PERFORMANCE_MONITORING_ENABLED=false --refresh-dependencies --stacktrace
  - ./gradlew assemble uploadArchives -PLOCAL_UPLOAD=false -PRELEASE_BUILD_TYPE_ENABLED=true -PRELEASE_FAKE_ENABLED=true --refresh-dependencies --stacktrace

after_script: sh ./etc/scripts/uploadReports.sh
